# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as a service called "app".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
#services:
#  docker-mysql:
#    image: mysql:latest
#    environment:
#      - MYSQL_ROOT_PASSWORD=sogyo
#      - MYSQL_USER=root
#      - MYSQL_DATABASE=ip
#      - MYSQL_PASSWORD=sogyo
#    ports:
#      -3307:3306
#  app:
#    image: catan:latest
#    ports:
#      8080:8080
#    environment:
#      SPRING_DATASOURCE_URL:
    # If your application exposes a port, uncomment the following lines and change
    # the port numbers as needed. The first number is the host port and the second
    # is the port inside the container.
    # ports:
    #   - 8080:8080

    # The commented out section below is an example of how to define a PostgreSQL
    # database that your application can use. `depends_on` tells Docker Compose to
    # start the database before your application. The `db-data` volume persists the
    # database data between container restarts. The `db-password` secret is used
    # to set the database password. You must create `db/password.txt` and add
    # a password of your choosing to it before running `docker compose up`.
    #     depends_on:
    #       db:
    #         condition: service_healthy
    #   db:
    #     image: postgres
    #     restart: always
    #     user: postgres
    #     secrets:
    #       - db-password
    #     volumes:
    #       - db-data:/var/lib/postgresql/data
    #     environment:
    #       - POSTGRES_DB=example
    #       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    #     expose:
    #       - 5432
    #     healthcheck:
    #       test: [ "CMD", "pg_isready" ]
    #       interval: 10s
    #       timeout: 5s
    #       retries: 5
    # volumes:
    #   db-data:
    # secrets:
    #   db-password:
    #     file: db/password.txt

version: "3"
services:
  backend:
    image: "back-end"
    container_name: "back-end"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL:  jdbc:mysql://db:3306/ip
    networks:
      - springmysql-net
    depends_on:
      - db

  db:
    image: mysql
    container_name: "mysql"
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=sogyo
      - MYSQL_DATABASE=ip
    ports:
      - "3300:3306"

  frontend:
    image: "front-end"
    container_name: "front-end"
    ports:
      - "3000:3000"

networks:
  springmysql-net:
